### ISSUE TITLE
rakudo website ought to be https

### ISSUE THREAD

**Issue by tbrowder** [perl6/web-rakudo#1]
it's a download site and insecure

**Comment by zoffixznet** [comment]
Thanks for reminding me. I need to switch the download page to use https://rakudo.perl6.org/ Should be able to do that before next release.

As for the rest of the site... there's [a ticket for it](https://rt.perl.org/Ticket/Display.html?id=128423#ticket-history) but it seems there's some trouble catching @pmichaud and them having enough time to do the switch to HTTPS as well as upgrade all the software on the server.

**Comment by AlexDaniel** [comment]
I think this will be resolved once the website is moved (this should happen relatively soon).

**Comment by zoffixznet** [comment]
Yup.
